Ignore C901 (cyclomatic complexity) when linting
aiven/aiven-client pull request #264
Opened 2022-01-22 23:10 UTC by vladan

# About this change: What it does, why it matters

Building packages for Fedora 35 (`python 3.10.2`) breaks with:
```
+ make test
make[3]: Entering directory '/var/home/vladan/rpmbuild/BUILD/aiven-client'
fatal: not a git repository (or any parent up to mount point /var/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /var/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /var/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
python3 -m flake8 aiven tests
aiven/client/client.py:1619:5: C901 'AivenClient.create_project' is too complex (12)
aiven/client/client.py:1675:5: C901 'AivenClient.update_project' is too complex (12)
aiven/client/client.py:1854:5: C901 'AivenClient.create_billing_group' is too complex (13)
aiven/client/client.py:1908:5: C901 'AivenClient.update_billing_group' is too complex (14)
aiven/client/cli.py:205:5: C901 'AivenCLI.create_user_config' is too complex (13)
aiven/client/cli.py:846:5: C901 'AivenCLI.service__plans' is too complex (12)
aiven/client/cli.py:1840:5: C901 'AivenCLI.service__user_creds_download' is too complex (11)
aiven/client/cli.py:3743:5: C901 'AivenCLI.service__create' is too complex (11)
aiven/client/cli.py:3979:5: C901 'AivenCLI.service__update' is too complex (12)
aiven/client/argx.py:212:5: C901 'CommandLineTool.print_response' is too complex (13)
aiven/client/pretty.py:86:1: C901 'yield_table' is too complex (25)
aiven/client/connection_info/_utils.py:25:1: C901 'format_uri' is too complex (11)
make[3]: *** [Makefile:30: flake8] Error 1
make[3]: Leaving directory '/var/home/vladan/rpmbuild/BUILD/aiven-client'
error: Bad exit status from /var/tmp/rpm-tmp.YPXhnf (%check)
```

This change ignores `C901` and lets the build pass successfully generating an RPM.

2022-01-23 09:11 UTC, mhoffm-aiven commented
Why does it call a linter when building packages in the check step though? Maybe its better to have `make lint` and `make test` and seperate the linter calls into the `make lint` target. I can see value in the complaint.

2022-01-24 09:07 UTC, rominf requested changes
Instead of avoiding getting linting errors, it's better to just fix these functions. They are indeed complex and fixable...

2022-01-24 09:13 UTC, rikonen commented
I don't think refactoring code should be pre-requisite for supporting new Fedora version. If we didn't enforce cyclomatic complexity before then I think correct fix is to start by ignoring the errors and if we want to start enforcing it then make another pull request that enables the check and fixes the issues.

2022-01-24 09:27 UTC, mhoffm-aiven commented
> I don't think refactoring code should be pre-requisite for supporting new Fedora version. If we didn't enforce cyclomatic complexity before then I think correct fix is to start by ignoring the errors and if we want to start enforcing it then make another pull request that enables the check and fixes the issues.

As far as i understand we did enforce it but some limit changed when using the new python version. Thats why i want to suggest dropping linting checks as a prerequisite of building the package, but keeping them as a CI check.

2022-01-24 09:32 UTC, vladan commented
Having lints removed from the `test` target really makes sense, it is a common practice to run tests while building the package, but linting shouldn't be of concern at that point.

On a side note, I think we should run all released python versions (e.g. python 3.11 as well) in the CI, regardless if it's distro packaged, or not.

2022-01-24 09:49 UTC, rikonen commented
`make rpm` shouldn't run tests at all imo but the `test` target looks somewhat reasonable, runs all types of tests including static checks.

If some default changes then I wonder is there config option we can set to explicitly define what's the current max complexity instead of having checks fail randomly.

2022-01-25 10:30 UTC, mhoffm-aiven approved these changes
lgtm

2022-01-25 10:30 UTC, merged